In [1]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.4)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.13.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.71.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.8.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.13.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.0.9)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.4.26)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.8)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("/content/Attrition - Attrition.csv")

In [15]:
df.head(3)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0

In [16]:
 df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [17]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [23]:
categorical_features = ['BusinessTravel',
                       'Department',
                       'EducationField',
                       'Gender', 'JobRole', 'MaritalStatus',
                       'Over18','OverTime']

In [24]:
x =df.drop(columns = ['Attrition'] , axis=1)
y = df['Attrition']

In [25]:
x_encoded = pd.get_dummies(x, columns=categorical_features ,
                           drop_first=True)

In [26]:
categorical_features

['BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

In [27]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score

In [28]:
# encode target data
lb = LabelEncoder()

In [29]:
y_encoded = lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x_encoded,
                                                    y_encoded,
                                                    test_size=0.2, random_state=42)

In [31]:
sc = StandardScaler()

In [32]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

In [33]:
#now we will create architecture of our model

In [35]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=128, activation='relu',
                          input_dim=x_train_scaled.shape[1]),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=1, activation='sigmoid')  #output layer

])

In [36]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']

In [37]:
learning_rate = 0.001
momentum =0.9
optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate,
                                    momentum=momentum , nesterov = True)

In [38]:
model.compile(optimizer=optimizer, loss=loss_fn, metrics=metrics)

In [39]:
#training the data

In [40]:
model.fit(x_train_scaled,
          y_train,
          epochs=50,
          batch_size=8,
          validation_split=0.1)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6465 - loss: 0.6359 - val_accuracy: 0.7966 - val_loss: 0.4881
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7930 - loss: 0.5094 - val_accuracy: 0.7966 - val_loss: 0.4638
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8419 - loss: 0.4243 - val_accuracy: 0.8051 - val_loss: 0.4412
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8240 - loss: 0.4317 - val_accuracy: 0.8051 - val_loss: 0.4296
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8515 - loss: 0.3843 - val_accuracy: 0.8136 - val_loss: 0.4166
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8555 - loss: 0.3832 - val_accuracy: 0.8305 - val_loss: 0.4088
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8671 - loss: 0.3555 - val_accuracy: 0.8220 - val_loss: 0.4040
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8632 - loss: 0.3547 - val_accuracy: 0.8136 - val_loss: 0.3999
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8593 - loss: 0.3660 - val_accuracy: 0.8136 - val_loss: 0.3970
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8545 - loss: 0.3746 - val_accuracy: 0.8051 - val_loss: 0.3966
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8648 - loss: 0.3521 - val_accuracy: 0.8220 - val_loss: 0.3947
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8861 - loss: 0.3179 - val_accuracy: 0.8220 - val_loss: 0.3944
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8579 - loss: 0.3523 - val_accuracy: 0.8305 - val_loss: 0.3934
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8714 - loss: 0.3277 - val_accuracy: 0.8305 - val_loss: 0.3911
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8723 - loss: 0.2976 - val_accuracy: 0.8305 - val_loss: 0.3933
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8662 - loss: 0.3112 - val_accuracy: 0.8220 - val_loss: 0.3926
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8673 - loss: 0.3246 - val_accuracy: 0.8220 - val_loss: 0.3947
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8791 - loss: 0.2960 - val_accuracy: 0.8220 - val_loss: 0.3945
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8722 - loss: 0.2879 - val_accuracy: 0.8220 - val_loss: 0.3937
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8907 - loss: 0.2706 - val_accuracy: 0.8305 - val_loss: 0.3953
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8908 - loss: 0.2664 - val_accuracy: 0.8051 - val_loss: 0.3977
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.8922 - loss: 0.2676 - val_accuracy: 0.8136 - val_loss: 0.3999
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8755 - loss: 0.2925 - val_accuracy: 0.8220 - val_loss: 0.4009
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8776 - loss: 0.3016 - val_accuracy: 0.8220 - val_loss: 0.3968
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8810 - loss: 0.2729 - val_accuracy: 0.8305 - val_loss: 0.4022
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8853 - loss: 0.2718 - val_accuracy: 0.8220 - val_loss: 0.3994
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8929 - loss: 0.2544 - val_accuracy: 0.8136 - val_loss: 0.4052
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9015 - loss: 0.2550 - val_accuracy: 0.8220 - val_loss: 0.4061
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9097 - loss: 0.2558 - val_accuracy: 0.8220 - val_loss: 0.4070
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9196 - loss: 0.2456 - val_accuracy: 0.8220 - val_loss: 0.4085
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8997 - loss: 0.2467 - val_accuracy: 0.8220 - val_loss: 0.4116
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8855 - loss: 0.2474 - val_accuracy: 0.8220 - val_loss: 0.4099
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9190 - loss: 0.2220 - val_accuracy: 0.8220 - val_loss: 0.4138
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9042 - loss: 0.2380 - val_accuracy: 0.8305 - val_loss: 0.4201
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9036 - loss: 0.2325 - val_accuracy: 0.8220 - val_loss: 0.4249
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9224 - loss: 0.2010 - val_accuracy: 0.8136 - val_loss: 0.4293
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9189 - loss: 0.2157 - val_accuracy: 0.8136 - val_loss: 0.4403
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9031 - loss: 0.2256 - val_accuracy: 0.8051 - val_loss: 0.4394
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9129 - loss: 0.2104 - val_accuracy: 0.7966 - val_loss: 0.4378
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9078 - loss: 0.2446 - val_accuracy: 0.8220 - val_loss: 0.4332
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9345 - loss: 0.1853 - val_accuracy: 0.8220 - val_loss: 0.4367
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9131 - loss: 0.2226 - val_accuracy: 0.8136 - val_loss: 0.4408
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9274 - loss: 0.1998 - val_accuracy: 0.8051 - val_loss: 0.4367
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9293 - loss: 0.1825 - val_accuracy: 0.8136 - val_loss: 0.4442
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9135 - loss: 0.2202 - val_accuracy: 0.8136 - val_loss: 0.4440
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9289 - loss: 0.1905 - val_accuracy: 0.8220 - val_loss: 0.4427
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9205 - loss: 0.2160 - val_accuracy: 0.8136 - val_loss: 0.4535
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9152 - loss: 0.2102 - val_accuracy: 0.8136 - val_loss: 0.4527
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1885 - val_accuracy: 0.8220 - val_loss: 0.4525
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9270 - loss: 0.1990 - val_accuracy: 0.7966 - val_loss: 0.4605

In [41]:
loss , accuracy = model.evaluate(x_test_scaled, y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8740 - loss: 0.3674

In [42]:
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy:.4f}')

Test Loss: 0.3579
Test Accuracy: 0.8741